version = "3.8.6"
runner.dialect = scala3

maxColumn = 100

rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
rewrite.rules = [SortImports, RedundantParens, SortModifiers]
